"""Writes samples/chime.wav: a short synthesized two-note chime (48 kHz mono 16-bit), the sample clip of the release.

Needs numpy. The output is deterministic, so the tracked file can be regenerated byte for byte.
"""
import os
import wave

import numpy as np

RATE = 48000


def bell(freq, start, length, total):
    """A bell-like note: a few inharmonic partials with exponential decay and a soft attack."""
    t = np.arange(int(length * RATE)) / RATE
    partials = [(1.0, 1.0, 1.4), (2.0, 0.45, 2.2), (2.76, 0.25, 3.2), (5.4, 0.12, 5.0), (8.93, 0.05, 7.0)]
    note = np.zeros_like(t)
    for ratio, amp, decay in partials:
        note += amp * np.sin(2 * np.pi * freq * ratio * t) * np.exp(-decay * t)
    note *= 1 - np.exp(-t / 0.004)  # 4 ms attack, no click
    out = np.zeros(total)
    i = int(start * RATE)
    out[i:i + len(note)] += note[: total - i]
    return out


def main():
    total = int(2.6 * RATE)
    signal = bell(659.25, 0.0, 2.6, total) + 0.9 * bell(523.25, 0.45, 2.15, total)  # E5, C5
    fade = np.ones(total)
    fade[-int(0.3 * RATE):] = np.linspace(1, 0, int(0.3 * RATE))
    signal *= fade
    signal *= 0.5 / np.max(np.abs(signal))  # peak at -6 dBFS
    pcm = np.round(signal * 32767).astype('<i2')

    path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'samples', 'chime.wav')
    with wave.open(path, 'wb') as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(RATE)
        w.writeframes(pcm.tobytes())
    print(f'{path}: {len(pcm) / RATE:.2f} s')


if __name__ == '__main__':
    main()
